export const basemapItems = [
  { value: 'arcgis/navigation', text: 'arcgis/navigation' },
  { value: 'arcgis/navigation-night', text: 'arcgis/navigation-night' },
  { value: 'arcgis/satellite', text: 'arcgis/satellite', selected: true },
  { value: 'arcgis/streets', text: 'arcgis/streets' },
  { value: 'arcgis/streets-relief', text: 'arcgis/streets-relief' },
  { value: 'arcgis/streets-night', text: 'arcgis/streets-night' },
  { value: 'arcgis/outdoor', text: 'arcgis/outdoor' },
  { value: 'arcgis/imagery', text: 'arcgis/imagery' },
  { value: 'arcgis/topographic', text: 'arcgis/topographic' },
  { value: 'arcgis/terrain', text: 'arcgis/terrain' },
  { value: 'arcgis/oceans', text: 'arcgis/oceans' },
  { value: 'arcgis/light-gray', text: 'arcgis/light-gray' },
  { value: 'arcgis/dark-gray', text: 'arcgis/dark-gray' },
  { value: 'arcgis/human-geography', text: 'arcgis/human-geography' },
  { value: 'arcgis/human-geography-dark', text: 'arcgis/human-geography-dark' },
  { value: 'arcgis/charted-territory', text: 'arcgis/charted-territory' },
  { value: 'arcgis/colored-pencil', text: 'arcgis/colored-pencil' },
  { value: 'arcgis/nova', text: 'arcgis/nova' },
  { value: 'arcgis/modern-antique', text: 'arcgis/modern-antique' },
  { value: 'arcgis/midcentury', text: 'arcgis/midcentury' },
  { value: 'arcgis/newspaper', text: 'arcgis/newspaper' },
  { value: 'osm/standard', text: 'osm/standard' },
  { value: 'osm/standard-relief', text: 'osm/standard-relief' },
  { value: 'osm/navigation', text: 'osm/navigation' },
  { value: 'osm/navigation-dark', text: 'osm/navigation-dark' },
  { value: 'osm/streets', text: 'osm/streets' },
  { value: 'osm/hybrid', text: 'osm/hybrid' },
  { value: 'osm/light-gray', text: 'osm/light-gray' },
  { value: 'osm/dark-gray', text: 'osm/dark-gray' },
  { value: 'osm/blueprint', text: 'osm/blueprint' }
]
